version: '3.7' 
services: 
  mongo:
    container_name: mongo
    restart: always
    image: mongo:4.2.0 
    volumes:
      - ./data:/data/db  
#    healthcheck:
#        test:  echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
#        interval: 10s
#        timeout: 10s
#        retries: 5
#        start_period: 40s
    networks:
      - nodejs-mongo
      
  nodejs-app: 
    container_name: nodejs-app
    restart: on-failure
    build: test-files 
    ports: 
      - '3000:3000'
    environment:
      - MONGO_PORT=27017 
    depends_on:
      - mongo
    networks:
      - nodejs-mongo

networks:
  nodejs-mongo: